// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVt7RDgrIIeYXi6WrBXYLMHp7BnFVNCDU',
    appId: '1:721093293596:android:9032e157b0324e530211d9',
    messagingSenderId: '721093293596',
    projectId: 'iw-reminder',
    databaseURL: 'https://iw-reminder-default-rtdb.firebaseio.com',
    storageBucket: 'iw-reminder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxlcOH1pN1ZZh8W8D8MUcNlt2RkgbeW8c',
    appId: '1:721093293596:ios:98908817f52f5cab0211d9',
    messagingSenderId: '721093293596',
    projectId: 'iw-reminder',
    databaseURL: 'https://iw-reminder-default-rtdb.firebaseio.com',
    storageBucket: 'iw-reminder.firebasestorage.app',
    iosBundleId: 'com.iwlabs.reminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxlcOH1pN1ZZh8W8D8MUcNlt2RkgbeW8c',
    appId: '1:721093293596:ios:98908817f52f5cab0211d9',
    messagingSenderId: '721093293596',
    projectId: 'iw-reminder',
    databaseURL: 'https://iw-reminder-default-rtdb.firebaseio.com',
    storageBucket: 'iw-reminder.firebasestorage.app',
    iosBundleId: 'com.iwlabs.reminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1lJkfibMjSWXjsfGSseEdktxS99KyUIg',
    appId: '1:721093293596:web:22cac218eee266750211d9',
    messagingSenderId: '721093293596',
    projectId: 'iw-reminder',
    authDomain: 'iw-reminder.firebaseapp.com',
    databaseURL: 'https://iw-reminder-default-rtdb.firebaseio.com',
    storageBucket: 'iw-reminder.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1lJkfibMjSWXjsfGSseEdktxS99KyUIg',
    appId: '1:721093293596:web:cac81b11a4cd9f140211d9',
    messagingSenderId: '721093293596',
    projectId: 'iw-reminder',
    authDomain: 'iw-reminder.firebaseapp.com',
    databaseURL: 'https://iw-reminder-default-rtdb.firebaseio.com',
    storageBucket: 'iw-reminder.firebasestorage.app',
  );
}
